doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # server_version: '13'

        # only needed for MySQL
        # charset: utf8mb4
        #default_table_options:
        #    collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Surfnet\ServiceProviderDashboard:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Surfnet/ServiceProviderDashboard/Domain/Entity"
                prefix: Surfnet\ServiceProviderDashboard\Domain\Entity
                alias: SurfnetServiceProviderDashboard
