doctrine_migrations:
    migrations_paths:
        'Surfnet\ServiceProviderDashboard\Migrations': '%kernel.project_dir%/migrations'

    storage:
            table_storage:
                table_name: 'migration_versions'
                version_column_name: 'version'
                version_column_length: 192

    organize_migrations: false
    em:
        default
