framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    templating:
        engines: [ 'twig' ]
    trusted_hosts: ~
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    php_errors:
        log: true
