framework:
    secret: '%env(APP_SECRET)%'
    handle_all_throwables: true
    annotations:
        enabled: false
    csrf_protection: true
    trusted_hosts: ~
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: '%env(session_max_absolute_lifetime)%'
        gc_maxlifetime: '%env(session_max_relative_lifetime)%'
    esi: false
    fragments: false
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    php_errors:
        log: true
