#    swiftmailer:
#        url: '%env(MAILER_URL)%'
#        spool: { type: 'memory' }

# Swiftmailer Configuration
swiftmailer:
    transport: '%env(mailer_transport)%'
    host: '%env(mailer_host)%'
    username: '%env(mailer_user)%'
    password: '%env(mailer_password)%'
    spool: { type: memory }

