twig:
    paths:
        '%kernel.project_dir%/templates': 'Dashboard'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locale: "%env(locale)%"
        logout: "%env(logout_redirect_url)%"
