---
services:
  spdashboard:
    image:  ghcr.io/openconext/openconext-basecontainers/php82-apache2-node20-composer2:latest
    environment:
      APP_ENV: ci
      PHP_MEMORY_LIMIT: 256M
    volumes:
      - ${PWD}/../OpenConext-devconf/core/:/config
      - ${PWD}/:/var/www/html/
      - ${PWD}/docker/conf/zz-docker.conf:/usr/local/etc/php/conf.d/zz-docker.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      coreconextdev:
    hostname: spdashboard.docker
    depends_on:
      engine:
        condition: service_healthy
      mariadb:
        condition: service_healthy

  cypress:
    image: cypress/included:15.11.0
    working_dir: /e2e
    entrypoint: cypress open --project .
    networks:
      coreconextdev:
    volumes:
      - ${PWD}:/e2e
