include: 
  - ../OpenConext-devconf/core/docker-compose.yml

services:
    spdashboard:
      image:  ghcr.io/openconext/openconext-basecontainers/php82-apache2-node20-composer2:latest
      environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      volumes:
        - ../OpenConext-devconf/core/:/config
        - ./:/var/www/html/
        - ./docker/conf/zz-docker.conf:/usr/local/etc/php/conf.d/zz-docker.ini
      extra_hosts:
        - "host.docker.internal:host-gateway"
      networks:
        coreconextdev:
      hostname: spdashboard.docker
      depends_on:
        engine:
          condition: service_healthy
        mariadb:
          condition: service_healthy
