include: 
  - ../OpenConext-devconf/core/docker-compose.yml

services:
    spdashboard:
      image:  ghcr.io/openconext/openconext-basecontainers/php82-apache2-node20-composer2:latest
      environment:
      - APP_ENV=dev
      volumes:
        - ../OpenConext-devconf/core/:/config
        - ./:/var/www/html/
      networks:
        coreconextdev:
      hostname: spdashboard.docker
      depends_on:
        engine:
          condition: service_healthy
        mariadb:
          condition: service_healthy
