imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: logging.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator:
        fallbacks: ['%locale%']
        logging: false
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/build/manifest.json'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            surfnet_serviceproviderdashboard:
                type: annotation
                is_bundle: false
                dir: "%kernel.root_dir%/../src/Surfnet/ServiceProviderDashboard/Domain/Entity"
                prefix: Surfnet\ServiceProviderDashboard\Domain\Entity
                alias: SurfnetServiceProviderDashboard

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true

lexik_translation:
    fallback_locale: [en] # (required) default locale(s) to use
    managed_locales: [en] # (required) locales that the bundle has to manage
    grid_input_type: textarea
    grid_toggle_similar: true
    resources_registration:
        type: all
        managed_locales_only: true
    base_layout: "::Translation/layout.html.twig"

stfalcon_tinymce:
    tinymce_jquery: false
    language: "%locale%"
    theme:
        simple:
            theme: "modern"
            menubar: false
            toolbar: "bold italic underline | styleselect | bullist numlist outdent indent | link"
            plugins:
                - "autolink lists link contextmenu paste"

surfnet_saml:
    hosted:
        service_provider:
            enabled: true
            assertion_consumer_route: dashboard_saml_consume_assertion
            public_key: "%saml_sp_publickey%"
            private_key: "%saml_sp_privatekey%"
        metadata:
            entity_id_route: dashboard_saml_metadata
            public_key: "%saml_metadata_publickey%"
            private_key: "%saml_metadata_privatekey%"
    remote:
        identity_provider:
            enabled: true
            entity_id: "%saml_remote_idp_entity_id%"
            sso_url: "%saml_remote_idp_sso_url%"
            certificate: "%saml_remote_idp_certificate%"

dashboard:
    manage:
        test:
            connection:
                host: "%manage_test_host%"
                username: "%manage_test_username%"
                password: "%manage_test_password%"
            publication_status: "%manage_test_publication_status%"
        production:
            connection:
                host: "%manage_prod_host%"
                username: "%manage_prod_username%"
                password: "%manage_prod_password%"
            publication_status: "%manage_prod_publication_status%"

dashboard_saml:
    session_lifetimes:
        max_absolute_lifetime: "%session_max_absolute_lifetime%"
        max_relative_lifetime: "%session_max_relative_lifetime%"
    administrator_teams: "%administrator_teams%"

tactician:
    commandbus:
        default:
            middleware:
                - surfnet.dashboard.middleware.doctrine_transaction
                - tactician.middleware.command_handler