framework:
#  router:
#    resource: '%kernel.root_dir%/config/routes_dev.yaml'
#    strict_requirements: true
  profiler: { only_exceptions: false }
  session:
    save_path: '/tmp/sp-dashboard-sessions'
