monolog:
    handlers:
        prod-signaler:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: DEBUG # DEV setting: this means that all message of level DEBUG or higher are always logged
            #passthru_level: NOTICE # PROD setting this means that all message of level NOTICE or higher are always logged
            handler: main_syslog
            bubble: true
        main_syslog:
            type: syslog
            ident: spdashboard
            facility: user
            channels: ['!event']
            formatter: Surfnet\ServiceProviderDashboard\Infrastructure\DashboardBundle\Monolog\Formatter\JsonFormatter
        main_logfile:
            type: stream
            handler: logfile
            level: NOTICE
            path: "%kernel.logs_dir%/%kernel.environment%.log"
