certs_sp_dashboard: yes
engine_crt_not_in_inventory: true
shibd_sp_crt_not_in_inventory: true
develop: false
minimal_install: false
haproxy_backend_tls: false
timezone: Europe/Amsterdam
base_domain: dev.support.surfconext.nl
apache_app_listen_address:
  all: 127.0.0.1
support_email: root@localhost
apache_server_admin: root@localhost
instance_name: "OpenConext dev"  
mysql_root_password: secret
mariadb_host: localhost
mysql_host: localhost
spd_mysql_passwords:
  spregistration: secret
  sr: secret
spd_databases:
  names:
    - spregistration
    - "{{ janus_database_name }}"
  users:
   - { name: sprw, db_name: spregistration, password: "{{ spd_mysql_passwords.spregistration }}" }
   - { name: "{{ janus_database_user }}", db_name: "{{ janus_database_name }}", password: "{{ mysql_passwords.sr }}" }

database_clients: [ "{{ mysql_host }}" ]

support_simplesaml_secret: secret
mongo_primary: True

spdashboard:
  adminteams:
    - 'urn:collab:org:dev.support.surfconext.nl'

spdashboard_saml_remote_idp_entity_id: "https://engine.{{ base_domain }}/authentication/idp/metadata"
spdashboard_saml_remote_idp_sso_url: "https://engine.{{ base_domain }}/authentication/idp/single-sign-on"
spdashboard_saml_remote_idp_certificate: "MIIDuDCCAqCgAwIBAgIJAPdqJ9JQKN6vMA0GCSqGSIb3DQEBBQUAMEYxDzANBgNVBAMTBkVuZ2luZTERMA8GA1UECxMIU2VydmljZXMxEzARBgNVBAoTCk9wZW5Db25leHQxCzAJBgNVBAYTAk5MMB4XDTE1MDQwMjE0MDE1NFoXDTI1MDQwMTE0MDE1NFowRjEPMA0GA1UEAxMGRW5naW5lMREwDwYDVQQLEwhTZXJ2aWNlczETMBEGA1UEChMKT3BlbkNvbmV4dDELMAkGA1UEBhMCTkwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCeVodghQwFR0pItxGaJ3LXHA+ZLy1w/TMaGDcJaszAZRWRkL/6djwbabR7TB45QN6dfKOFGzobQxG1Oksky3gz4Pki1BSzi/DwsjWCw+Yi40cYpYeg/XM0tvHKVorlsx/7Thm5WuC7rwytujr/lV7f6lavf/ApnLHnOORU2h0ZWctJiestapMaC5mc40msruWWp04axmrYICmTmGhEy7w0qO4/HLKjXtWbJh71GWtJeLzG5Hj04X44wI+D9PUJs9U3SYh9SCFZwq0v+oYeqajiX0JPzB+8aVOPmOOM5WqoT8OCddOM/TlsL/0PcxByGHsgJuWbWMI1PKlK3omR764PAgMBAAGjgagwgaUwHQYDVR0OBBYEFLowmsUCD2CrHU0lich1DMkNppmLMHYGA1UdIwRvMG2AFLowmsUCD2CrHU0lich1DMkNppmLoUqkSDBGMQ8wDQYDVQQDEwZFbmdpbmUxETAPBgNVBAsTCFNlcnZpY2VzMRMwEQYDVQQKEwpPcGVuQ29uZXh0MQswCQYDVQQGEwJOTIIJAPdqJ9JQKN6vMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAIF9tGG1C9HOSTQJA5qL13y5Ad8G57bJjBfTjp/dw308zwagsdTeFQIgsP4tdQqPMwYmBImcTx6vUNdiwlIol7TBCPGuqQAHD0lgTkChCzWezobIPxjitlkTUZGHqn4Kpq+mFelX9x4BElmxdLj0RQV3c3BhoW0VvJvBkqVKWkZ0HcUTQMlMrQEOq6D32jGh0LPCQN7Ke6ir0Ix5knb7oegND49fbLSxpdo5vSuxQd+Zn6nI1/VLWtWpdeHMKhiw2+/ArR9YM3cY8UwFQOj9Y6wI6gPCGh/q1qv2HnngmnPrNzZik8XucGcf1Wm2zE4UIVYKW31T52mqRVDKRk8F3Eo="
spdashboard_manage_prod_host: "https://manage-prod.{{ base_domain}}"
spdashboard_jira_username: api_spdashboard_user
spdashboard_playground_uri_test: "https://authz-playground.{{ base_domain }}/redirect"
spdashboard_playground_uri_prod: "https://authz-playground-prod.{{ base_domain }}/redirect"
spdashboard_jira_assignee: username

engine_janus_secret: secret
engine_api_janus_user: serviceregistry
engine_api_janus_password: secret
engine_api_domain: engine-api.{{ base_domain }}
engine_keys:
  default:
    privateFile: /etc/openconext/engineblock.pem
    publicKey: engineblock.crt
    publicFile: /etc/openconext/engineblock.crt
engine_version: 5.2.3
engine_apache_environment: vm
engine_apache_symfony_environment: prod
engine_feature_ldap_integration: 0

tls:
  cert_path: /etc/pki/tls/certs
  cert_path_ca: /etc/pki/ca-trust/source/anchors/
  cert_private_path: /etc/pki/tls/private
tls_star_cert: star.{{ base_domain }}.pem
tls_star_cert_key: star.{{ base_domain }}.key
tls_ca: star.{{ base_domain }}_ca.pem

https_dev_star_private_key: |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDCJManJ2FCyC+K
  BJ8MakQhyMHbX41tEIc93SSMFTEd0foqD2wJfU5E3vCSN5oB4Tg9tMQ7RlCFmlNv
  qt/swnrYv3VxncxSFx+X40jXFUPdC+t+CmCFfRK4rUgj73+89/SEevscb7Rn1aCa
  //MiilHSbsQqpzuL0IBg7+tlC7GrI4/H/es7vhUD/nD/jTk0okdjxEl9JnG2OnPW
  hId1Ng9Ow7RkHGxgxHRAHGhv8VwO/Qk2N56BXf73l5o78XQu9HKoSj2vlgg3ZD4Q
  rN9NBs7FQVxNJ+w35qpw6q7q296/ctX8g8G6ikgi50IhzD2sDH9uTs6eBUJI6mZY
  HE5v8jc7AgMBAAECggEAZKMTpsovDKMgoXbLy2+6aZjbhI//i62prVPZAhRqJX8X
  In5kDnc5/1Fheyn/V0IcGUB/CArm6pqY7aWx9dTKQVjd1EtsApGh+uYCeBu51fe7
  1tYiOpAfCEQqxRX9LUOLKLFnQdJVvg1q92395sW0rFRms4WExHEMWzOC3ho1uvQH
  Xe/4RPy9YbTSJRS8DS8ZKCfSNx73fFkuorFr+aw6RcmZp/uc9KgVIHywr516wWJu
  yTSESBKczhoCM5/z/6DV/aYtH439OgsdY9fLscu2P75SXO1QXK87+8kujo1FMFAJ
  5k4UsAj/m8LZCF1RcWo36HoeYGWH/3G34ENTfMSZIQKBgQD7mrAQmceivJ6vF+4H
  tsT6dcEFU9/rCmMcF7jJzN3iQUXKBLbbr1374NaqodQgVAHefgBDao7hyPoBum9a
  EcrbnGy8oPITYPiOqoVzhYYEjSeg1gTp9tOdTXe/tvX3uR8FHLAfVXvL0knyRTC5
  d3MHEDfRpsAH0r7kXhL9ZOnZdwKBgQDFiRfKvYkSWNcP/VU3FW1dJuoUVUZLoJfP
  Ybcp4Dof1coesCOLzs++kdZ6CuUuPDFkUxfvqCoTzWpCxLWtuYkJ/bJwlht+3BW5
  HN5jqLOzQTMBhar4xj80e1Xrb9pMru9lCXvWQQYMY+MdrjNUlwRn2/rIjzBtVbGO
  cNV5MTFBXQKBgAhF9uIk3F6qiyFAzS/tv55ovtcZAfTtm4Kx+P6RwP4OnWfeLdEd
  fB6rLwPfXGVPvdv+Eq4k09vyyt3BrqWsjhoYk67EMBGZD7NJQighTN3bcmEkiHbV
  CfJTOMvSDVZ+/NkjL1toaTCzkoDn64k9t0eVLfCz5f6b3HEP8tnoNpRTAoGAQgrG
  uJLLvCWVqZPiJKt2R/mVszybZveHKd+alFaSOEiK7d2n1LtNO4KYuW7hFqcrQEaD
  ry2C++Hmj/IiZ7WrOnrmaLvW73/3h08+jwU9J0Y6Hl0pP0lQomRF4pQf4RlvklEs
  ZQKSWhwfN7IhGTvwTiT+4IT3BObsmRniVUV8GUUCgYEAmHx0zUHu8bYnuAubCKCb
  puPf4bBZcllbbCknk87ZJz3gl9fe7a6PiBmbFEPdh0UEoJCK5o3I9PpM32f6jbYa
  oTaOuSW9U6XhN+VIzTFjHL+N4+H4t0tfpagfVESm8mJmnjnKvBam+zd8G4jubFMF
  N1pOK9PSfCUpJTfJ95BRMe8=
  -----END PRIVATE KEY-----

engineblock_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEAnlaHYIUMBUdKSLcRmidy1xwPmS8tcP0zGhg3CWrMwGUVkZC/
  +nY8G2m0e0weOUDenXyjhRs6G0MRtTpLJMt4M+D5ItQUs4vw8LI1gsPmIuNHGKWH
  oP1zNLbxylaK5bMf+04ZuVrgu68Mrbo6/5Ve3+pWr3/wKZyx5zjkVNodGVnLSYnr
  LWqTGguZnONJrK7llqdOGsZq2CApk5hoRMu8NKjuPxyyo17VmyYe9RlrSXi8xuR4
  9OF+OMCPg/T1CbPVN0mIfUghWcKtL/qGHqmo4l9CT8wfvGlTj5jjjOVqqE/DgnXT
  jP05bC/9D3MQchh7ICblm1jCNTypSt6Jke+uDwIDAQABAoIBAQCCwSH6auSKV1zY
  v5UhoAIN8XZQIc18yRsyKV0JwdBj8RXmp4ph4tGwMZKBX1J2JUOw+gRvHxTU/oXZ
  CtKTCBOzg805Hboaqy3FFuVpnyylEtrbV5axM5u3pHv3g5AgL9PxS4Wis5FybBQk
  Qu4FsewvLO148EX7lxKyxyCHkbcF/vxGLj+eNboka4hlah2vVz2cHO3Yp4QKOfIh
  p02ij0Hvlwv9FVhvQghy8xFfCD9Nfh3QRUXpHhob1WPFLJWNTf14SVOtfCKbB5z4
  LyvJ+TqIwB7cMPEhHfvyH+26s43wRwmGzr5xAdaNVu04NiXDW/s/b4ebuD3BZbpk
  yx8tUDrBAoGBANEf9ia9LKj4fya7H0TTyUxfUREZUDOALCcPfeiZEibQ3ZawaLOa
  ci3W0jRl90NFpajDQQli5V1/DCmWFcvHarejInFYIG+QLWrKwCPNkrJ1Qccz4VLZ
  TffzuhhMNd1KAUXuYPqvm/KSnwGf+rVxCVMojHpbJDQ9LgCovY4oANtrAoGBAMHU
  TsEWV5uF/enj1co5LlhNMotP2D3+2F1bdGBd5iPU+X38NghSei9oA9KOtaJBN1fo
  +7ELUxxm/Bw9L8BaOQUHC9NWk87kSfRAxEx6AsWGdOW6GNQknYKCf3iX+xTcow76
  GgtigZiENQOwZAtDpw9Q5ZPNR8Vv9ig5W0cOvKTtAoGBALMrFATKrTmzdZTkWvzo
  Cp4hR95DdsA4/xsUHcarZq7U4hSZ3YqLN2nolD4KYldDk5PMfasiDOsWz3/Ns6zc
  lKTy4q6DV37d4tuNDCNgnF/DMHEQFOubfD6ElZr9qGSIZCDbBEGjNRQV5J9Kxkyv
  pNKXegvWjGUpSYGNEKJ7yYgzAoGBAJHyTdZ//zlgvB8X6cuaILZmck+JsHaF5N7u
  1QMW0Qpb+/yMIxdDGzOE65Po1wU0e/qauKHHuC3jsaOFwuXgSZzqgFICl8sqBDGB
  bw1ytZGLu4ubA8UBSQSTRG5Gac18kN7fHStDYfe4XL7JW5tLtogGzsbqxEb7FeuV
  vJAVnZ/FAoGANJ+h6hUdN0t4IjHl6DRr+x2gniqYLCRS/DpkOi6fj2LVIqG7xWt/
  fg946ohBj8jA7wt8JNkgL6Bxn3uqdFFGvr0IudJHvpuPFOnKPeL0/Pa7U94d15L4
  aLEj+8OAOJ3LWJrvJQY1HuGBl7yc2Z+9UO8o41peMfqJXnJCAbPGqXg=
  -----END RSA PRIVATE KEY-----

maven_repo: https://build.openconext.org/repository/public/releases
maven_snapshot_repo: https://build.openconext.org/repository/public/snapshots
error_subject_prefix: "[{{ ansible_hostname }}] "

# Some engineblock variables are shared between applications
engine_api_metadata_push_user: serviceregistry

# Some deprovision variables are shared between applications
authz_server_api_lifecycle_username: authz_server_api_lifecycle_user
teams_api_lifecycle_username: teams_api_lifecycle_user
attribute_aggregator_api_lifecycle_username: attribute_aggregator_api_lifecycle_user
engine_api_deprovision_user: lifecycle
