services:
  _defaults:
    public: true

  Surfnet\ServiceProviderDashboard\Infrastructure\DashboardBundle\DataFixtures\:
    resource: '%kernel.project_dir%/src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DataFixtures'
    autowire: true
    autoconfigure: true

parameters:
  # By enabling 'jira_enable_test_mode', no real Jira backend is required to still simulate the Jira integration
  jira_enable_test_mode: true
