dashboard:
  resource: '@DashboardBundle/Resources/config/routing.yml'

dashboard_saml:
  resource: "@DashboardSamlBundle/Controller/"
  prefix:   /

openconext_monitor:
  resource: "@OpenConextMonitorBundle/Resources/config/routing.yml"
  prefix: /

lexik_translation_edition:
  resource: "@LexikTranslationBundle/Resources/config/routing.yml"
  prefix:   /translations

nelmio_security_csp:
  path:     /csp/report
  defaults: { _controller: nelmio_security.csp_reporter_controller:indexAction }
  methods:  [POST]
