#!/usr/bin/env sh
# attributes data check

cd $(dirname $0)/../../

# https://www.npmjs.com/package/ajv-cli
./node_modules/.bin/ajv validate -s app/Resources/schemas/attributes.scheme.json -d app/config/attributes.json
