#!/usr/bin/env sh

# Make sure every command returns an error if tests fail
set -e

cd $(dirname $0)/../../

# PHPUnit Bridge should always be used in Symfony applications. (https://symfony.com/doc/current/components/phpunit_bridge.html)
# This will create a phpunit executable in /bin/ instead of /vendor/bin/
./vendor/bin/phpunit -c ci/qa/phpunit.xml --testsuite unit
./vendor/bin/phpunit -c ci/qa/phpunit.xml --testsuite integration
