name: Build docker container for the SP Dashboard

on:
  pull_request:
  release:
    types: [ published ]
  push: 
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker metadata for php fpm container
        id: metaphpfpm
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/surfnet/sp-dashboard/spdashboard_php-fpm
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set docker metadata for web container
        id: metahttpd
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/surfnet/sp-dashboard/spdashboard_web
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build the php-fpm container and push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.metaphpfpm.outputs.tags }}
          target: phpfpm-build

      - name: Build the Apache container and push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.metahttpd.outputs.tags }}
          target: httpd-build
