name: PHP test suite

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    # Due to the cgroups 1 issue on the openconext container, we do not
    # use the new ubuntu platform yet. As they started using cgroups v2
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DOCKER_COMPOSE: docker compose -f docker-compose.yml -f docker-compose-php-tests.yml
      DOCKER_COMPOSE_PHP: docker compose -f docker-compose.yml -f docker-compose-php-tests.yml exec -T spdashboard
      DOCKER_RUN_SPD_AS_WWW: docker compose -f docker-compose.yml -f docker-compose-php-tests.yml exec --user 33:33 spdashboard

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6.0.2
        with:
          path: spdashboard

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: spdashboard/yarn.lock

      - name: Checkout openconext-devconf
        uses: actions/checkout@v6.0.2
        with:
          repository: OpenConext/OpenConext-devconf
          ref: main
          path: devconf
          sparse-checkout: core

      - name: Bootstrap the openconext environment
        working-directory: devconf/core
        run: ./scripts/init.sh

      - name: Start the docker images for testing
        working-directory: spdashboard
        run: ${DOCKER_COMPOSE} up -d mariadb spdashboard test-browser

      - name: Instantiate the env file
        run: cp spdashboard/.env.dist spdashboard/.env

      - name: Run composer
        working-directory: spdashboard
        run: |
          ${DOCKER_COMPOSE_PHP} /usr/bin/composer install -n --prefer-dist -o --ignore-platform-reqs

      - name: Install frontend dependencies and build assets
        working-directory: spdashboard
        run: |
          yarn install
          yarn build

      - name: Run CI tests
        working-directory: spdashboard
        run: |
          ${DOCKER_COMPOSE_PHP} sh -c 'composer webtest'

      - name: Upload error screenshots
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: error-screenshots
          path: spdashboard/var/error-screenshots
          retention-days: 2
